apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
    annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: "250M"
        nginx.ingress.kubernetes.io/proxy-read-timeout: "90"
        nais.io/read-only-file-system: "false"
        nais.io/run-as-user: "1001"
    name: routing
    namespace: aap
    labels:
        team: aap
spec:
    observability:
        tracing:
            enabled: true
    accessPolicy:
        inbound:
            rules:
                -   application: demo
                    namespace: helseopplysninger
        outbound:
            rules:
                -   application: demo
                -   application: skjermede-personer-pip
                    namespace: nom
                -   application: tempo-distributor
                    namespace: nais-system
            external:
                -   host: unleash.nais.io
                -   host: nav-it.slack.com
                -   host: aap-fss-proxy.{{env}}-fss-pub.nais.io
                -   host: pdl-api.{{env}}-fss-pub.nais.io
                -   host: saf.{{env}}-fss-pub.nais.io
                -   host: dokarkiv.{{env}}-fss-pub.nais.io
                -   host: oppgave.{{env}}-fss-pub.nais.io
    secureLogs:
        enabled: true
    azure:
        application:
            enabled: true
    kafka:
        pool: nav-{{env}}
    port: 8080
    cpuThresholdPercentage: 50
    image: {{image}}
    liveness:
        path: /actuator/health/liveness
        initialDelay: 60
    readiness:
        path: /actuator/health/readiness
        initialDelay: 60
    prometheus:
        enabled: true
        path: /actuator/prometheus
    replicas:
        min: 2
        max: 2
        cpuThresholdPercentage: 50
    ingresses:
        - {{ingress}}
    resources:
        limits:
            memory: 3072Mi
        requests:
            cpu: 250m
            memory: 1536Mi
    env:
        -   name: ENV
            value: {{env}}
        -   name: SUFFIX
            value: {{suffix}}
    envFrom:
        -   secret: slack