debug: false
management:
    endpoints:
        web:
            exposure:
                include: '*'
    endpoint:
        health:
            show-details: always
        shutdown:
            enabled: true

saf:
    base-uri: https://safselvbetjening-q1.dev-fss-pub.nais.io
joark:
    hendelser:
        topic: teamdokumenthandtering.aapen-dok-journalfoering-q1
    scope: api://dev-fss.teamdokumenthandtering.saf-q1/.default
    saf-uri: https://saf-q1.${env}-fss-pub.nais.io/graphql