info:
    nais:
        clientid: ${nais.client.id}
        project: ${gcp.team.project.id}
        cluster: ${nais.cluster.name}
        image: ${nais.app.image}
        app: ${nais.app.name}
        namespace: ${nais.namespace}

spring:
    cloud:
        gcp:
            project-id: ${gcp.team.project.id}
    codec:
        max-in-memory-size: 50MB
    devtools:
        restart:
            enabled: false
        add-properties: false
        livereload:
            enabled: false
    kafka:
        bootstrap-servers: ${kafka.brokers}
        properties:
            basic:
                auth:
                    user:
                        info: ${kafka.schema.registry.user}:${kafka.schema.registry.password}
                    credentials:
                        source: USER_INFO
            schema:
                registry:
                    url: ${kafka.schema.registry}
            ssl:
              endpoint:
                identification:
                    algorithm: ''
        security:
            protocol: SSL
        ssl:
            trust-store-location: file:${kafka.truststore.path}
            trust-store-type: JKS
            trust-store-password: ${kafka.credstore.password}
            key-store-location: file:${kafka.keystore.path}
            key-store-type: PKCS12
            key-store-password: ${kafka.credstore.password}
        consumer:
            group-id: ${spring.application.name}-${env}
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
            properties:
                specific:
                    avro:
                        reader: true
        producer:
            client-id: ${spring.application.name}
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
            acks: 1
            properties:
              max:
                request:
                    size: 2000000
no.nav:
    security:
        jwt:
            client:
                registration:
                    arena:
                        token-endpoint-url: ${azure.openid.config.token.endpoint}
                        grant-type: client_credentials
                        scope: ${arena.scope}
                        authentication:
                            client-id: ${azure.app.client.id}
                            client-jwk: ${azure.app.jwk}
                            client-auth-method: private_key_jwt
                    egenansatt:
                        token-endpoint-url: ${azure.openid.config.token.endpoint}
                        grant-type: client_credentials
                        scope: ${egenansatt.scope}
                        authentication:
                            client-id: ${azure.app.client.id}
                            client-jwk: ${azure.app.jwk}
                            client-auth-method: private_key_jwt
                    oppgave:
                        token-endpoint-url: ${azure.openid.config.token.endpoint}
                        grant-type: client_credentials
                        scope: ${oppgave.scope}
                        authentication:
                            client-id: ${azure.app.client.id}
                            client-jwk: ${azure.app.jwk}
                            client-auth-method: private_key_jwt
                    pdl:
                        token-endpoint-url: ${azure.openid.config.token.endpoint}
                        grant-type: client_credentials
                        scope: ${pdl.scope}
                        authentication:
                            client-id: ${azure.app.client.id}
                            client-jwk: ${azure.app.jwk}
                            client-auth-method: private_key_jwt
                    saf:
                        token-endpoint-url: ${azure.openid.config.token.endpoint}
                        grant-type: client_credentials
                        scope: ${saf.scope}
                        authentication:
                            client-id: ${azure.app.client.id}
                            client-jwk: ${azure.app.jwk}
                            client-auth-method: private_key_jwt
                    dokarkiv:
                        token-endpoint-url: ${azure.openid.config.token.endpoint}
                        grant-type: client_credentials
                        scope: ${dokarkiv.scope}
                        authentication:
                            client-id: ${azure.app.client.id}
                            client-jwk: ${azure.app.jwk}
                            client-auth-method: private_key_jwt
            issuer:
                aad:
                    discoveryurl: ${azure.app.well.known.url}
                    accepted_audience: ${azure.app.client.id}


navorg:
    base-uri: https://norg2.${env}-fss-pub.nais.io
egenansatt:
    base-uri: http://skjermede-personer-pip.nom
    scope: api://${env}-gcp.nom.skjermede-personer-pip/.default
dokarkiv:
    base-uri: https://dokarkiv.${env}-fss-pub.nais.io
    scope: api://${env}-fss.teamdokumenthandtering.dokarkiv${suffix}/.default
saf:
    base-uri: https://saf.${env}-fss-pub.nais.io/graphql
    scope: api://${env}-fss.teamdokumenthandtering.saf${suffix}/.default
pdl:
    base-uri: https://pdl-api.${env}-fss-pub.nais.io/graphql
    scope: api://${env}-fss.pdl.pdl-api/.default
arena:
    base-uri: https://aap-fss-proxy.${env}-fss-pub.nais.io
    scope: api://${env}-fss.aap.fss-proxy/.default
oppgave:
    base-uri: https://oppgave${suffix}.${env}-fss-pub.nais.io
    scope: api://${env}-fss.oppgavehandtering.oppgave${suffix}/.default
fordeling:
    topics:
        main: teamdokumenthandtering.aapen-dok-journalfoering${suffix}
        retries: 24