debug: false
management:
    endpoints:
        web:
            exposure:
                include: '*'
    endpoint:
        health:
            show-details: always
        shutdown:
            enabled: true
saf:
   scope: api://dev-fss.teamdokumenthandtering.saf-q1/.default
dokarkiv:
    scope: api://dev-fss.teamdokumenthandtering.dokarkiv-q1/.default
fordeling:
    topics:
        main: teamdokumenthandtering.aapen-dok-journalfoering-q1
oppgave:
    base-uri: https://oppgave-q1.dev-fss-pub.nais.io
    scope: api://dev-fss.oppgavehandtering.oppgave-q1/.default