debug: false
management:
    endpoints:
        web:
            exposure:
                include: '*'
    endpoint:
        health:
            show-details: always
        shutdown:
            enabled: true
joark:
    dokarkiv: https://dokarkiv.${env}-fss-pub.nais.io
    hendelser:
        topic: teamdokumenthandtering.aapen-dok-journalfoering-q1
    scope: api://dev-fss.teamdokumenthandtering.saf-q1/.default
navorg:
    base-uri: https://norg2.dev-fss-pub.nais.io
    enabled: true
arena:
    enabled: true
    base-uri: https://aap-fss-proxy.${dev}-fss-pub.nais.io