management:
    endpoints:
        web:
            exposure:
                include: '*'
    endpoint:
        health:
            show-details: always
fordeling:
    topics:
        backoff: 2000:
debug: true