fordeling:
    enabled: true
    topics:
        backoff: 2000
debug: false
management:
  endpoint:
    chaosmonkey:
        enabled: true
chaos:
    monkey:
      apidoc:
          enabled: true
      enabled: true
      watcher:
          service: true
          rest-controller: true
          web-client: true
          component: true
      assaults:
          latency-active: true
          exceptions-active: true
          kill-application-active: true