info:
    nais:
        clientid: ${nais.client.id}
        project: ${gcp.team.project.id}
        cluster: ${nais.cluster.name}
        image: ${nais.app.image}
        app: ${nais.app.name}
        namespace: ${nais.namespace}

resilience4j:
    retry:
        instances:
            graphql:
                max-attempts: 3
                waitDuration: 100ms
                ignoreExceptions:
                    - no.nav.aap.routing.arkiv.graphql.GraphQLExtensions.UnrecoverableGraphQL
spring:
    cloud:
        gcp:
            project-id: ${gcp.team.project.id}
    devtools:
        restart:
            enabled: false
        add-properties: false
        livereload:
            enabled: false
    kafka:
        bootstrap-servers: ${kafka.brokers}
        properties:
            basic:
                auth:
                    user:
                        info: ${kafka.schema.registry.user}:${kafka.schema.registry.password}
                    credentials:
                        source: USER_INFO
            schema:
                registry:
                    url: ${kafka.schema.registry}
            ssl:
              endpoint:
                identification:
                    algorithm: ''
        security:
            protocol: SSL
        ssl:
            trust-store-location: file:${kafka.truststore.path}
            trust-store-type: JKS
            trust-store-password: ${kafka.credstore.password}
            key-store-location: file:${kafka.keystore.path}
            key-store-type: PKCS12
            key-store-password: ${kafka.credstore.password}
        consumer:
            group-id: ${spring.application.name}-${env}
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
            properties:
                specific:
                    avro:
                        reader: true
        producer:
            acks: all
            client-id: ${spring.application.name}
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringDeserializer

no.nav:
    security:
        jwt:
            client:
                registration:
                    skjerming:
                        token-endpoint-url: ${azure.openid.config.token.endpoint}
                        grant-type: client_credentials
                        scope: ${skjerming.scope}
                        authentication:
                            client-id: ${azure.app.client.id}
                            client-jwk: ${azure.app.jwk}
                            client-auth-method: private_key_jwt
                    pdl:
                        token-endpoint-url: ${azure.openid.config.token.endpoint}
                        grant-type: client_credentials
                        scope: ${pdl.scope}
                        authentication:
                            client-id: ${azure.app.client.id}
                            client-jwk: ${azure.app.jwk}
                            client-auth-method: private_key_jwt
                    joark:
                        token-endpoint-url: ${azure.openid.config.token.endpoint}
                        grant-type: client_credentials
                        scope: ${joark.scope}
                        authentication:
                            client-id: ${azure.app.client.id}
                            client-jwk: ${azure.app.jwk}
                            client-auth-method: private_key_jwt
            issuer:
                aad:
                    discoveryurl: ${azure.app.well.known.url}
                    accepted_audience: ${azure.app.client.id}

egenansatt:
    enabled: true
    base-uri: http://skjermede-personer-pip.nom
    scope: api://skjermede-personer-pip.nom/.default
joark:
    enabled: true
    base-uri: ${saf}
pdl:
    enabled: true
    base-uri: https://pdl-api.${env}-fss-pub.nais.io/graphql
    scope: api://${env}-fss.pdl.pdl-api/.default