server:
    error:
        whitelabel:
            enabled: false

resilience4j:
    retry:
        instances:
            saf:
                max-attempts: 10
                waitDuration: 1s
                retryExceptions:
                    - org.springframework.web.reactive.function.client.WebClientResponseException
                    - no.nav.aap.fordeling.graphql.GraphQLExtensions.RecoverableIntegrationException
                ignoreExceptions:
                    - no.nav.aap.fordeling.graphql.GraphQLExtensions.UnrecoverableIntegrationException
            pdl:
                max-attempts: 10
                waitDuration: 1s
                retryExceptions:
                    - org.springframework.web.reactive.function.client.WebClientResponseException
                    - no.nav.aap.fordeling.graphql.GraphQLExtensions.RecoverableIntegrationException
                ignoreExceptions:
                    - no.nav.aap.fordeling.graphql.GraphQLExtensions.UnrecoverableIntegrationException
spring:
    cache:
        cache-names: navorg
        caffeine:
            spec: maximumSize=1,expireAfterAccess=3600s
    application:
        name: routing
    main:
        banner-mode: off
    cloud:
        discovery:
            client:
                health-indicator:
                    enabled: false
    jackson:
        default-property-inclusion: non_empty
        mapper:
            accept-case-insensitive-enums: true
            accept-case-insensitive-properties: true
        deserialization:
            accept-empty-array-as-null-object: true
            read-unknown-enum-values-using-default-value: true
            accept-single-value-as-array: true
            fail-on-unknown-properties: true
        serialization:
            write-empty-json-arrays: true
            fail-on-empty-beans: false
management:
    endpoints:
        web:
            exposure:
                include: '*'
    endpoint:
      configprops:
          show-values: always
      env:
          additional-keys-to-sanitize: "client-jwk,jwk,jwks"
          show-values: always
    info:
        os:
            enabled: true
        java:
            enabled: true
        env:
            enabled: true
    health:
        ping:
            enabled: false
        diskspace:
            enabled: false
fordeling:
    enabled: false
springdoc:
    packagesToScan: no.nav.aap
    swagger-ui:
        disable-swagger-default-url: true
    show-actuator: true
    enable-spring-security: false