debug: false
management:
    endpoints:
        web:
            exposure:
                include: '*'
    endpoint:
        health:
            show-details: always
        shutdown:
            enabled: true
joark:
    hendelser:
        topic: teamdokumenthandtering.aapen-dok-journalfoering-q1
    scope: api://dev-fss.teamdokumenthandtering.saf-q1/.default
    dokarkivscope: api://dev-fss.teamdokumenthandtering.dokarkiv-q1/.default


oppgave:
    base-uri: https://oppgave-q1.dev-fss-pub.nais.io
    scope: api://dev-fss.oppgavehandtering.oppgave-q1/.default