management:
    endpoints:
        web:
            exposure:
                include: '*'
    endpoint:
        health:
            show-details: always
fordeling:
    enabled: true
    topics:
        backoff: 2000
debug: false