pool: nav-prod
config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 2
    partitions: 12
    replication: 3
    retentionBytes: -1
    retentionHours: 120
acl:
    -   team: aap
        application: routing
        access: write