name: Bygg og deploy

on:
    push:
        branches:
            - main
        paths-ignore:
            - '**.md'
env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    IMAGE_BASE: ghcr.io/${{ github.repository }}

jobs:
    bygg:
        runs-on: ubuntu-latest
        outputs:
            image: ${{ steps.kompiler.outputs.image }}
        steps:
            -   name: Sjekker ut kode
                uses: actions/checkout@v3


            -   name: Setter opp Java 17
                uses: actions/setup-java@v3
                with:
                    java-version: 17
                    distribution: temurin
                    cache: maven

            -   name: Installerer cosign
                uses: sigstore/cosign-installer@main
                with:
                    cosign-release: 'v1.3.1'

            -   name: Verifiserer distroless base-image
                run:  cosign verify --key distroless.pub gcr.io/distroless/java17

            -   name: Setter tag-navn
                run: echo "TAG=$(date +%Y.%m.%d.%H%M%S)-$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

            -   name: Setter image-navn
                run: echo "IMAGE=$(echo $IMAGE_BASE):$(echo $TAG)" >> $GITHUB_ENV

            -   name: Kompilerer og bygger image
                id: kompiler
                run: |
                    echo "image=${{ env.IMAGE }}" >> $GITHUB_OUTPUT
                    ./mvnw --settings .github/.m2/settings.xml -Drevision=${TAG} package jib:build

    deploy:
        strategy:
            matrix:
                cluster: [dev-gcp,prod-gcp]
        name: Deploy til ${{matrix.cluster}}
        needs: bygg
        runs-on: ubuntu-latest
        environment: ${{matrix.cluster}}:aap
        env:
            PRINT_PAYLOAD: true
            TIMEOUT: 30m
            APIKEY: ${{secrets.NAIS_DEPLOY_APIKEY}}
            RESOURCE: .nais/naiserator.yaml,.nais/${{matrix.cluster}}-alerts.yaml
            CLUSTER: ${{matrix.cluster}}
            VARS: .nais/${{matrix.cluster}}.json
            IMAGE: ${{needs.bygg.outputs.image}}
        steps:
            - uses: actions/checkout@v3
            - uses: nais/deploy/actions/deploy@v1