name: Bygg og deploy

on:
    push:
        branches:
            - main
        paths-ignore:
            - '**.md'
env:
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    IMAGE_BASE: europe-north1-docker.pkg.dev/${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}/aap/${{ github.event.repository.name }}

jobs:
    bygg:
        permissions:
            contents: write
            id-token: write
        runs-on: ubuntu-latest
        outputs:
            image: ${{ steps.kompiler.outputs.image }}
        steps:
            -   name: Sjekker ut kode
                uses: actions/checkout@v3

            -   name: Setter opp Java 17
                uses: actions/setup-java@v3
                with:
                    java-version: 17
                    distribution: temurin
                    cache: maven

            -   name: Cache SonarCloud packages
                uses: actions/cache@v3
                with:
                    path: ~/.sonar/cache
                    key: ${{ runner.os }}-sonar
                    restore-keys: ${{ runner.os }}-sonar

            -   name: Installerer cosign
                uses: sigstore/cosign-installer@main
                with:
                    cosign-release: v1.3.1

            -   name: Verifiserer distroless base-image
                run: cosign verify --key distroless.pub gcr.io/distroless/java17

            -   name: Setter tag-navn
                run: echo "TAG=$(date +%Y.%m.%d.%H%M%S)-$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

            -   name: Setter image-navn
                run: echo "IMAGE=$(echo $IMAGE_BASE)-$(echo $TAG)" >> $GITHUB_ENV

            -   name: Login GAR
                uses: nais/login@v0
                with:
                    project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
                    identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
                    team: aap

            -   name: Submit Dependency Snapshot
                uses: advanced-security/maven-dependency-submission-action@v3
                with:
                    settings-file: .github/.m2/settings.xml

            -   name: Kompilerer, bygger  og pusher image
                id: kompiler
                run: |
                    echo "image=${{ env.IMAGE }}:${{ env.TAG }}" >> $GITHUB_OUTPUT
                    ./mvnw --settings .github/.m2/settings.xml -DGAR_TOKEN=${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }} -Djib.to.tags=${TAG} -Drevision=${TAG} sonar:sonar -Dsonar.projectKey=navikt_aap-routing package jib:build 
                     echo "DIGEST=$(cat target/jib-image.digest)" >> $GITHUB_ENV

            -   name: Attest and sign
                uses: nais/attest-sign@v1.0.0
                with:
                    image_ref: ${{ env.IMAGE }}@${{ env.DIGEST }}
    deploy:
        strategy:
            matrix:
                cluster: [ dev-gcp,prod-gcp ]
        name: Deploy til ${{matrix.cluster}}
        needs: bygg
        runs-on: ubuntu-latest
        environment: ${{matrix.cluster}}:aap
        env:
            PRINT_PAYLOAD: true
            TIMEOUT: 30m
            APIKEY: ${{secrets.NAIS_DEPLOY_APIKEY}}
            RESOURCE: .nais/naiserator.yaml,.nais/${{matrix.cluster}}-alerts.yaml
            CLUSTER: ${{matrix.cluster}}
            VARS: .nais/${{matrix.cluster}}.json
            IMAGE: ${{needs.bygg.outputs.image}}
        steps:
            -   uses: actions/checkout@v3
            -   uses: nais/deploy/actions/deploy@v1