name: Build PR or branch

on:
    pull_request:
        branches:
            - main
        paths-ignore:
            - '**.md'
env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    IMAGE_BASE: europe-north1-docker.pkg.dev/${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}/aap/${{ github.event.repository.name }}

jobs:
    bygg:
        permissions:
            contents: "read"
            id-token: "write"
        runs-on: ubuntu-latest
        outputs:
            image: ${{ steps.kompiler-pr.outputs.image }}
        steps:
            -  name: Print number of PR
               run: echo The Title of your PR is ${{ github.event.pull_request.number }}

            -   name: Sjekk ut kode
                uses: actions/checkout@v3


            -   name: Setter opp Java 17
                uses: actions/setup-java@v3
                with:
                    java-version: 17
                    distribution: temurin
                    cache: maven

            -   name: Setter tag-navn
                run: echo "TAG=$(date +%Y.%m.%d.%H%M%S)-$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

            -   name: Setter image-navn
                run: echo "IMAGE=$(echo $IMAGE_BASE)-$(echo $TAG)" >> $GITHUB_ENV


            -   name: Login GAR
                uses: nais/login@v0
                with:
                    project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
                    identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
                    team: aap

            -   name: Kompiler, bygg og deploy PR til dev-gcp
                id: kompiler-pr
                run: |
                    echo "image=${{ env.IMAGE }}" >> $GITHUB_OUTPUT
                    ./mvnw  -DGAR_TOKEN=${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }} --batch-mode --settings .github/.m2/settings.xml package jib:build 

    deploy:
        strategy:
            matrix:
                cluster: [ dev-gcp, prod-gcp ]
        name: Deploy PR til ${{matrix.cluster}}
        needs: bygg
        runs-on: ubuntu-latest
        environment: ${{matrix.cluster}}:aap
        env:
            PRINT_PAYLOAD: true
            TIMEOUT: 30m
            APIKEY: ${{secrets.NAIS_DEPLOY_APIKEY}}
            RESOURCE: .nais/naiserator.yaml,.nais/${{matrix.cluster}}-alerts.yaml
            CLUSTER: ${{matrix.cluster}}
            VARS: .nais/${{matrix.cluster}}.json
            IMAGE: ${{needs.bygg.outputs.image}}
        steps:
            -   uses: actions/checkout@v3
            -   uses: nais/deploy/actions/deploy@v1