name: Deploy kafka DLT topic

on:
  push:
    branches:
      - main
    paths:
      - dlt/**
  workflow_dispatch:

jobs:
  deploy:
    strategy:
      matrix:
        cluster: [ dev-gcp, prod-gcp ]
    name: Deploy DLT til ${{matrix.cluster}}
    runs-on: ubuntu-latest
    environment: ${{matrix.cluster}}:aap
    env:
      PRINT_PAYLOAD: true
      APIKEY: ${{secrets.NAIS_DEPLOY_APIKEY}}
    steps:
      -   uses: actions/checkout@v3
      -   name: deploy dlt to ${{matrix.cluster}}
          uses: nais/deploy/actions/deploy@v1
          env:
            APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
            CLUSTER: ${{matrix.cluster}}
            RESOURCE: dlt/topic.yaml
            VARS: dlt/${{matrix.cluster}}.yaml
            PRINT_PAYLOAD: true